export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const CLOCK_START = 'CLOCK_START';
export const CLOCK_CURRENT = 'CLOCK_CURRENT';

export const PLAY_VIDEO = 'PLAY_VIDEO';

export const SAVE_VIDEO_FAIL = 'SAVE_VIDEO_FAIL';
export const SAVE_VIDEO_SUCCESS = 'SAVE_VIDEO_SUCCESS';

export const FETCH_SAVED_VIDEO_FAIL = 'FETCH_SAVED_VIDEO_FAIL';
export const FETCH_SAVED_VIDEO_SUCCESS = 'FETCH_SAVED_VIDEO_SUCCESS';

export const LOAD_MORE_SUCCESS = 'LOAD_MORE_SUCCESS';
export const LOAD_MORE_FAIL = 'LOAD_MORE_FAIL';
